"""
PDF export for ExpenseIQ reports (CLEAN & SAFE VERSION)
- No custom font dependency (avoids TTF crashes)
- Works on all systems (Windows / Render / Linux)
"""

import io
import os
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER


def generate_expense_report_pdf(
    user_name,
    expenses,
    stats,
    category_breakdown,
    budgets,
    date_from=None,
    date_to=None
):
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        leftMargin=16 * mm,
        rightMargin=16 * mm,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "Title",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=20,
        spaceAfter=6,
    )

    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        textColor=colors.HexColor("#666666"),
        spaceAfter=10,
    )

    section_style = ParagraphStyle(
        "Section",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=13,
        spaceBefore=12,
        spaceAfter=6,
    )

    empty_style = ParagraphStyle(
        "Empty",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        textColor=colors.grey,
    )

    elements = []

    # ================= HEADER =================
    elements.append(Paragraph("ExpenseIQ — Expense Report", title_style))

    period = f"{date_from} to {date_to}" if date_from and date_to else "All time"
    generated = datetime.now().strftime("%d %b %Y, %I:%M %p")

    elements.append(
        Paragraph(f"{user_name} • Period: {period}", subtitle_style)
    )
    elements.append(
        Paragraph(f"Generated on {generated}", subtitle_style)
    )

    # ================= SUMMARY =================
    elements.append(Paragraph("Summary", section_style))

    summary_data = [
        ["Total Spent", "Transactions", "Top Category"],
        [
            f"₹{stats.get('total', 0)}",
            str(stats.get("count", 0)),
            stats.get("top_category", "-"),
        ],
    ]

    summary_table = Table(summary_data, colWidths=[60 * mm, 60 * mm, 60 * mm])
    summary_table.setStyle(_summary_style())
    elements.append(summary_table)

    # ================= CATEGORY =================
    elements.append(Paragraph("Category Breakdown", section_style))

    if category_breakdown:
        data = [["Category", "Amount", "%"]]
        for c in category_breakdown:
            data.append([
                c["name"],
                f"₹{c['amount']}",
                f"{c.get('percent', 0)}%",
            ])

        table = Table(data, colWidths=[60 * mm, 60 * mm, 60 * mm])
        table.setStyle(_table_style())
        elements.append(table)
    else:
        elements.append(Paragraph("No data available", empty_style))

    # ================= BUDGET =================
    if budgets:
        elements.append(Paragraph("Budget vs Actual", section_style))

        spent = {c["name"]: c["amount"] for c in category_breakdown}

        data = [["Category", "Budget", "Spent"]]

        for cat, amt in budgets.items():
            data.append([
                cat,
                f"₹{amt}",
                f"₹{spent.get(cat, 0)}",
            ])

        table = Table(data, colWidths=[60 * mm, 60 * mm, 60 * mm])
        table.setStyle(_table_style())
        elements.append(table)

    # ================= TRANSACTIONS =================
    elements.append(Paragraph("Transactions", section_style))

    if expenses:
        data = [["Date", "Category", "Description", "Amount"]]

        for e in expenses:
            data.append([
                e.get("date_display", ""),
                e.get("category", ""),
                e.get("description", ""),
                f"₹{e.get('amount', 0)}",
            ])

        table = Table(
            data,
            colWidths=[30 * mm, 35 * mm, 75 * mm, 35 * mm],
            repeatRows=1,
        )
        table.setStyle(_table_style(last_right_align=True))
        elements.append(table)
    else:
        elements.append(Paragraph("No transactions found", empty_style))

    # ================= FOOTER =================
    elements.append(Spacer(1, 10 * mm))

    footer = Paragraph(
        "Generated by ExpenseIQ",
        ParagraphStyle(
            "Footer",
            fontName="Helvetica",
            fontSize=8,
            alignment=TA_CENTER,
            textColor=colors.grey,
        ),
    )

    elements.append(footer)

    doc.build(elements)
    buffer.seek(0)
    return buffer


# ================= TABLE STYLES =================

def _summary_style():
    return TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.green),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("PADDING", (0, 0), (-1, -1), 6),
    ])


def _table_style(last_right_align=False):
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f2f2f2")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.whitesmoke]),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]

    if last_right_align:
        style.append(("ALIGN", (-1, 0), (-1, -1), "RIGHT"))

    return TableStyle(style)